FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}.build" build-date="{{ build_date }}"

{% block netcontrold_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block netcontrold_install %}{% endblock %}

{% set netcontrold_packages = [
        'openvswitch',
  ]
%}

{{ macros.install_packages(netcontrold_packages | customizable("packages")) }}

{% block netcontrold_source_install_python_pip %}
{{ macros.get_pip() }}
{% endblock %}

{% set netcontrold_pip_packages = [
    'netcontrold',
  ]
%}

RUN {{ macros.install_pip(netcontrold_pip_packages | customizable("pip_packages"), constraints = false) }}

ENTRYPOINT ["sh", "-c", "/bin/ncd_watch"]

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block netcontrold_footer %}{% endblock %}
